### ISSUE TITLE
无法联网

### ISSUE THREAD

**Issue by fsyinghua** [bilibilifmk/ESP_weather_Cube#2]
已经连接上WIFI_LINK_TOOL, 但搜索SSID，选中后，不会弹出输入密码框，无法继续。

**Comment by bilibilifmk** [comment]
该问题已经修复了 miui 和iOS不弹出密码框

**Comment by huipeng8** [comment]
电脑端使用Edge浏览器，一样会出现密码框弹不出来的问题，F12调整浏览器分辨率后出现弹框，感觉和浏览器分辨率有关系
