### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by kai-oss-code** [bilibilifmk/ESP_weather_Cube#5]
1.It would be great if it could support the automatic enter to the wifi configure mode in case of  failed to connect to WiFi
2.Separate binary mode and file system mode into two header file

**Comment by bilibilifmk** [comment]
1.First of all, SDK connection to the network may fail. If no WiFi connection is implemented, entering the configuration will lead to many security vulnerabilities
2.I also think this is reasonable
